version: "3"
services:
  app:
    entrypoint:
      - sleep
      - infinity
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    expose:
      - 3306